export interface NicheData {
  key: string;
  label: string;
  singular: string;
  audience: string;
  painPoints: string[];
  services: string[];
  socialPlatforms: string[];
  hashtagSets: string[][];
  contentPillars: string[];
  seoKeywords: { keyword: string; intent: string; difficulty: string; contentIdea: string }[];
  emailSubjectLines: string[];
  objections: { objection: string; response: string }[];
  coldOutreachAngles: string[];
  seasonalEvents: { month: string; event: string; postIdea: string }[];
}

export const NICHES: NicheData[] = [
  {
    key: "dentists",
    label: "Dental Practices",
    singular: "dental practice",
    audience: "local patients seeking dental care",
    painPoints: [
      "Patients don't show up for appointments",
      "New patient acquisition is expensive",
      "Competing with corporate dental chains",
      "Low Google review count hurting visibility",
      "Patients delaying treatment due to cost concerns",
    ],
    services: ["General dentistry", "Cosmetic dentistry", "Orthodontics", "Teeth whitening", "Dental implants", "Emergency dental care", "Pediatric dentistry", "Periodontics"],
    socialPlatforms: ["Instagram", "Facebook", "TikTok", "Google Business"],
    hashtagSets: [
      ["#DentalCare", "#HealthySmile", "#DentistLife", "#OralHealth", "#SmileMakeover"],
      ["#TeethWhitening", "#DentalImplants", "#CosmeticDentistry", "#DentistTips", "#DentalHygiene"],
      ["#SmileTransformation", "#FamilyDentist", "#DentalClinic", "#BrushYourTeeth", "#OralCare"],
    ],
    contentPillars: ["Patient education", "Before/after transformations", "Team spotlights", "Dental myths busted", "Treatment explainers", "Community involvement"],
    seoKeywords: [
      { keyword: "dentist near me", intent: "local", difficulty: "high", contentIdea: "Optimize Google Business Profile with photos, reviews, and services" },
      { keyword: "teeth whitening cost", intent: "commercial", difficulty: "medium", contentIdea: "Blog post: Complete guide to teeth whitening options and pricing" },
      { keyword: "how to fix a chipped tooth", intent: "informational", difficulty: "low", contentIdea: "Blog post: What to do when you chip a tooth (and treatment options)" },
      { keyword: "dental implants near me", intent: "local-commercial", difficulty: "high", contentIdea: "Landing page: Dental implants — process, cost, and financing options" },
      { keyword: "best toothpaste for sensitive teeth", intent: "informational", difficulty: "low", contentIdea: "Blog post: Dentist's guide to choosing the right toothpaste" },
      { keyword: "how often should you go to the dentist", intent: "informational", difficulty: "low", contentIdea: "Blog post: How often do you really need dental checkups?" },
      { keyword: "emergency dentist [city]", intent: "local-urgent", difficulty: "medium", contentIdea: "Landing page: Emergency dental care — same day appointments" },
      { keyword: "invisalign vs braces", intent: "commercial", difficulty: "medium", contentIdea: "Blog post: Invisalign vs braces — which is right for you?" },
      { keyword: "dental financing options", intent: "commercial", difficulty: "low", contentIdea: "Landing page: Affordable dental care — payment plans available" },
      { keyword: "pediatric dentist near me", intent: "local", difficulty: "medium", contentIdea: "Landing page: Kid-friendly dental care your children will love" },
    ],
    emailSubjectLines: [
      "Your smile deserves this (quick read)",
      "We saved a spot for you this week",
      "The #1 thing most patients forget",
      "Your teeth are trying to tell you something",
      "This 2-minute habit saves thousands in dental work",
    ],
    objections: [
      { objection: "It's too expensive", response: "We offer flexible payment plans starting at $X/month. Most patients are surprised at how affordable it is — and the cost of waiting is almost always higher." },
      { objection: "I'm afraid of the dentist", response: "You're not alone — dental anxiety is incredibly common. We offer sedation options and our team specializes in making nervous patients feel comfortable. We go at your pace." },
      { objection: "I don't have insurance", response: "No insurance? No problem. We have an in-house membership plan that covers cleanings, exams, and gives you 20% off all treatments. It typically saves patients $500+/year." },
      { objection: "I'll come in when it hurts", response: "By the time a tooth hurts, the treatment is usually 5-10x more expensive than if caught early. A $200 checkup today can prevent a $3,000 root canal tomorrow." },
    ],
    coldOutreachAngles: [
      "Noticed your practice has great reviews but your Google Business Profile could rank higher — I put together a quick audit",
      "I help dental practices fill cancellation gaps using automated reminders — typically reduces no-shows by 40%",
      "Your practice website loads in 6+ seconds — that's costing you patients. Here's a free speed report",
    ],
    seasonalEvents: [
      { month: "January", event: "New Year", postIdea: "New year, new smile! Book your first cleaning of the year. Start fresh with a healthy mouth." },
      { month: "February", event: "Valentine's Day", postIdea: "Give yourself the gift of a brighter smile this Valentine's Day. Teeth whitening special this month!" },
      { month: "March", event: "Spring cleaning", postIdea: "Spring cleaning isn't just for your house — schedule your spring dental cleaning today!" },
      { month: "April", event: "Oral Health Month", postIdea: "April is Oral Health Month! Here are 5 habits that will save your teeth (and your wallet)." },
      { month: "May", event: "Mother's Day", postIdea: "This Mother's Day, give Mom the gift of a healthy smile. Gift certificates available!" },
      { month: "June", event: "Summer break", postIdea: "Kids out of school? Perfect time for their dental checkup before summer fun begins!" },
      { month: "August", event: "Back to school", postIdea: "Back-to-school checklist: Supplies ✓ Haircut ✓ Dental checkup? Schedule before the rush!" },
      { month: "October", event: "Halloween", postIdea: "Halloween candy survival guide: Which treats are worst for your teeth (and what to grab instead)." },
      { month: "November", event: "Benefits deadline", postIdea: "Use it or lose it! Your dental benefits expire Dec 31. Don't leave money on the table." },
      { month: "December", event: "Holiday", postIdea: "Holiday smile ready? Quick whitening before your family photos. Limited appointments available!" },
    ],
  },
  {
    key: "restaurants",
    label: "Restaurants",
    singular: "restaurant",
    audience: "local diners and food enthusiasts",
    painPoints: [
      "Inconsistent foot traffic during slow periods",
      "Competition from delivery apps taking margins",
      "Difficulty getting and managing online reviews",
      "Staff turnover and recruitment challenges",
      "Food costs fluctuating unpredictably",
    ],
    services: ["Dine-in", "Takeout", "Catering", "Private events", "Delivery", "Meal kits"],
    socialPlatforms: ["Instagram", "TikTok", "Facebook", "Google Business"],
    hashtagSets: [
      ["#Foodie", "#LocalEats", "#RestaurantLife", "#FoodLover", "#SupportLocal"],
      ["#ChefSpecial", "#FoodPhotography", "#EatLocal", "#FreshFood", "#Yummy"],
      ["#DinnerTime", "#FoodComa", "#Brunch", "#HappyHour", "#FarmToTable"],
    ],
    contentPillars: ["Behind the kitchen", "Menu highlights", "Chef stories", "Customer features", "Seasonal specials", "Community events"],
    seoKeywords: [
      { keyword: "best restaurants near me", intent: "local", difficulty: "high", contentIdea: "Optimize Google Business Profile with updated menu, photos, hours" },
      { keyword: "restaurants open late [city]", intent: "local", difficulty: "medium", contentIdea: "Blog: Late night dining guide — our kitchen stays open" },
      { keyword: "catering services near me", intent: "local-commercial", difficulty: "medium", contentIdea: "Landing page: Catering for events — menus, pricing, booking" },
      { keyword: "private dining [city]", intent: "local-commercial", difficulty: "low", contentIdea: "Landing page: Host your next event at our private dining room" },
      { keyword: "best brunch spots [city]", intent: "local", difficulty: "medium", contentIdea: "Blog: Why our brunch menu is the talk of the neighborhood" },
      { keyword: "restaurant reservation [city]", intent: "local", difficulty: "medium", contentIdea: "Make reservations easy — add online booking to website" },
      { keyword: "healthy restaurants near me", intent: "local", difficulty: "medium", contentIdea: "Blog: Our fresh, locally-sourced menu options" },
      { keyword: "restaurant gift cards", intent: "commercial", difficulty: "low", contentIdea: "Landing page: Give the gift of great food — digital gift cards" },
      { keyword: "food delivery [city]", intent: "local", difficulty: "high", contentIdea: "Landing page: Order direct — skip the delivery app markup" },
      { keyword: "restaurant happy hour [city]", intent: "local", difficulty: "low", contentIdea: "Blog: Our happy hour deals you can't miss" },
    ],
    emailSubjectLines: [
      "Your table is waiting (literally)",
      "New menu drop — you're the first to know",
      "This dish sold out 3 times last week",
      "Bring this email for a free appetizer",
      "We missed you — here's 15% off your next visit",
    ],
    objections: [
      { objection: "It's too expensive to eat out", response: "We hear you — that's why we offer weekday lunch specials starting at $X and a happy hour menu that's incredibly affordable. Great food doesn't have to break the bank." },
      { objection: "I can just order delivery", response: "You absolutely can! But dining in means fresh-from-the-kitchen quality, no delivery fees, and the full experience. Plus, we have dine-in exclusive specials you won't find on apps." },
      { objection: "I have dietary restrictions", response: "We take that seriously. Our menu includes clearly marked options for gluten-free, vegetarian, vegan, and common allergens. Our chef is always happy to customize dishes." },
    ],
    coldOutreachAngles: [
      "Your restaurant photos on Google are from 2023 — updated photos increase click-through by 35%. I can help refresh them",
      "I noticed you're on 3 delivery apps but your own website doesn't take orders — you're losing 30% per order in commissions",
      "Your top competitor has 2x your Google reviews. Here's a simple system to close that gap in 60 days",
    ],
    seasonalEvents: [
      { month: "January", event: "New Year", postIdea: "New year, new menu! Come try our fresh seasonal dishes to start the year right." },
      { month: "February", event: "Valentine's Day", postIdea: "Valentine's dinner for two — our special prix fixe menu is live. Book now before it sells out!" },
      { month: "March", event: "St. Patrick's Day", postIdea: "Celebrate St. Patrick's Day with our special menu and drink features!" },
      { month: "May", event: "Mother's Day", postIdea: "Treat Mom to brunch she'll actually love. Mother's Day reservations are open!" },
      { month: "June", event: "Patio season", postIdea: "Patio season is HERE. Cold drinks, warm evenings, and great food. See you outside!" },
      { month: "July", event: "Summer", postIdea: "Beat the heat with our new summer cocktail menu and light bites." },
      { month: "September", event: "Fall menu", postIdea: "Fall flavors are back! Pumpkin, apple, and warm spices on our new seasonal menu." },
      { month: "October", event: "Halloween", postIdea: "Halloween dinner special: costume contest + themed cocktails this Saturday!" },
      { month: "November", event: "Thanksgiving", postIdea: "Skip the cooking this year — our Thanksgiving catering feeds the whole family." },
      { month: "December", event: "Holiday parties", postIdea: "Book your holiday party with us! Private dining, custom menus, full bar. Dates filling fast." },
    ],
  },
  {
    key: "real-estate",
    label: "Real Estate Agents",
    singular: "real estate business",
    audience: "home buyers, sellers, and investors",
    painPoints: [
      "Lead generation is expensive and inconsistent",
      "Long sales cycles with uncertain closings",
      "Standing out in a crowded market",
      "Managing listings across multiple platforms",
      "Building trust with first-time buyers",
    ],
    services: ["Buyer representation", "Seller listing", "Market analysis", "Investment consulting", "Property management", "Relocation assistance"],
    socialPlatforms: ["Instagram", "Facebook", "YouTube", "LinkedIn", "TikTok"],
    hashtagSets: [
      ["#RealEstate", "#HomeBuyer", "#DreamHome", "#JustListed", "#HouseHunting"],
      ["#Realtor", "#PropertyForSale", "#FirstTimeBuyer", "#OpenHouse", "#HomeOwner"],
      ["#RealEstateAgent", "#MillionDollarListing", "#HomeDesign", "#MovingDay", "#NewHome"],
    ],
    contentPillars: ["Market updates", "Home buying tips", "Listing showcases", "Neighborhood guides", "Client success stories", "Investment advice"],
    seoKeywords: [
      { keyword: "homes for sale [city]", intent: "local-commercial", difficulty: "high", contentIdea: "IDX-integrated landing page with current listings" },
      { keyword: "real estate agent near me", intent: "local", difficulty: "high", contentIdea: "Optimize Google Business Profile with testimonials and listings" },
      { keyword: "first time home buyer tips", intent: "informational", difficulty: "medium", contentIdea: "Blog: Complete first-time home buyer guide for [city]" },
      { keyword: "how much house can I afford", intent: "informational", difficulty: "medium", contentIdea: "Blog + calculator: How much home can you afford in [city]?" },
      { keyword: "best neighborhoods in [city]", intent: "informational", difficulty: "medium", contentIdea: "Blog series: Neighborhood guides with school ratings, amenities, prices" },
      { keyword: "sell my house fast [city]", intent: "commercial", difficulty: "medium", contentIdea: "Landing page: Sell your home in 30 days — our proven process" },
      { keyword: "real estate market [city]", intent: "informational", difficulty: "low", contentIdea: "Monthly blog: Market update — prices, inventory, and what it means for you" },
      { keyword: "home staging tips", intent: "informational", difficulty: "low", contentIdea: "Blog: 10 staging tips that help homes sell 20% faster" },
      { keyword: "closing costs explained", intent: "informational", difficulty: "low", contentIdea: "Blog: What are closing costs and how much should you expect?" },
      { keyword: "investment property [city]", intent: "commercial", difficulty: "medium", contentIdea: "Blog: Best areas for rental property investment in [city]" },
    ],
    emailSubjectLines: [
      "Just listed: This one won't last",
      "The market just shifted — here's what it means for you",
      "[City] housing update (this surprised me)",
      "3 homes under $X that just hit the market",
      "Your neighbor's home just sold for $X — curious what yours is worth?",
    ],
    objections: [
      { objection: "I can just use Zillow/Redfin", response: "Those are great for browsing, but they show the same listings as everyone else — often days late. I get you access to listings before they hit public sites, negotiate on your behalf, and handle the 47 steps between offer and keys." },
      { objection: "Agent fees are too high", response: "I understand the concern. My commission is earned: I handle pricing strategy, marketing, negotiations, inspections, appraisals, and closing. Statistically, agent-assisted sales net 13% more than FSBO — more than covering the fee." },
      { objection: "Now isn't a good time to buy/sell", response: "I hear this a lot, and timing the market perfectly is nearly impossible. What I can tell you is what the data says right now for your specific situation, and whether waiting actually costs you more in the long run." },
    ],
    coldOutreachAngles: [
      "I noticed your listing on [platform] has been sitting for 30+ days — I put together 3 quick changes that could generate more showings",
      "Your area just saw a 12% price increase this quarter. I can run a free market analysis on your home if you're curious about your equity",
      "I help agents like you generate 10+ leads/month from Instagram without paid ads — here's the exact framework",
    ],
    seasonalEvents: [
      { month: "January", event: "New Year", postIdea: "Is 2026 your year to buy a home? Here's a month-by-month action plan to make it happen." },
      { month: "March", event: "Spring market", postIdea: "Spring selling season is starting. If you're thinking of listing, the next 60 days are your golden window." },
      { month: "April", event: "Peak season", postIdea: "The spring market is heating up! New listings this week in [city] — save your favorite." },
      { month: "May", event: "Summer prep", postIdea: "Buying this summer? Get pre-approved now so you can move fast when you find the one." },
      { month: "June", event: "Moving season", postIdea: "Moving season is here! Tips for a smooth move from our team of local experts." },
      { month: "August", event: "Back to school", postIdea: "Need to be in a new school district by fall? There's still time — but act now." },
      { month: "September", event: "Fall market", postIdea: "The fall market is underrated. Less competition, motivated sellers, great deals. Let me show you." },
      { month: "October", event: "Rate changes", postIdea: "Mortgage rates just moved. Here's what it means for your buying power — free consultation." },
      { month: "November", event: "Year-end", postIdea: "Closing before Dec 31 could mean tax benefits. Let's run the numbers for your situation." },
      { month: "December", event: "Holiday", postIdea: "This holiday season, give your family the ultimate gift — a new home. Quiet showings this month." },
    ],
  },
  {
    key: "gyms",
    label: "Gyms & Fitness Centers",
    singular: "gym",
    audience: "fitness enthusiasts and people starting their health journey",
    painPoints: [
      "Member retention and cancellations",
      "Low trial-to-member conversion rate",
      "Competing with home workout apps",
      "Seasonal membership fluctuations",
      "Getting members to actually show up",
    ],
    services: ["Personal training", "Group classes", "Nutrition coaching", "Online training", "Youth programs", "Corporate wellness"],
    socialPlatforms: ["Instagram", "TikTok", "Facebook", "YouTube"],
    hashtagSets: [
      ["#FitnessMotivation", "#GymLife", "#Workout", "#FitFam", "#GymTime"],
      ["#PersonalTrainer", "#FitnessGoals", "#StrongNotSkinny", "#LiftHeavy", "#FitnessJourney"],
      ["#GymMotivation", "#WorkoutOfTheDay", "#FitLife", "#NoExcuses", "#TrainHard"],
    ],
    contentPillars: ["Workout tips", "Member transformations", "Nutrition advice", "Trainer spotlights", "Gym culture", "Challenge content"],
    seoKeywords: [
      { keyword: "gym near me", intent: "local", difficulty: "high", contentIdea: "Optimize Google Business with tours, class schedules, pricing" },
      { keyword: "personal trainer [city]", intent: "local-commercial", difficulty: "medium", contentIdea: "Landing page: Meet our certified personal trainers" },
      { keyword: "beginner workout plan", intent: "informational", difficulty: "medium", contentIdea: "Blog: Free 4-week beginner workout plan (no experience needed)" },
      { keyword: "how to lose weight at the gym", intent: "informational", difficulty: "medium", contentIdea: "Blog: The real guide to weight loss at the gym (from trainers who've seen it all)" },
      { keyword: "group fitness classes [city]", intent: "local", difficulty: "low", contentIdea: "Landing page: Group classes schedule — yoga, HIIT, spin, and more" },
      { keyword: "gym membership prices", intent: "commercial", difficulty: "medium", contentIdea: "Landing page: Transparent pricing — no hidden fees, cancel anytime" },
      { keyword: "best exercises for back pain", intent: "informational", difficulty: "low", contentIdea: "Blog: 5 gym exercises that actually help back pain" },
      { keyword: "home gym vs gym membership", intent: "informational", difficulty: "low", contentIdea: "Blog: Home gym vs membership — honest cost and results comparison" },
      { keyword: "corporate wellness programs", intent: "commercial", difficulty: "low", contentIdea: "Landing page: Corporate wellness packages for your team" },
      { keyword: "24 hour gym [city]", intent: "local", difficulty: "medium", contentIdea: "Landing page: Open 24/7 — work out on your schedule" },
    ],
    emailSubjectLines: [
      "Your gym misses you (we mean it)",
      "This 15-minute workout is all you need today",
      "New class alert: You're going to love this",
      "Your fitness goal is closer than you think",
      "Free guest pass inside — bring a friend this week",
    ],
    objections: [
      { objection: "I'm not fit enough to go to a gym", response: "That's exactly why you should come! Everyone starts somewhere. Our trainers specialize in beginners, and our community is incredibly supportive. No judgment, ever." },
      { objection: "I can work out at home", response: "You absolutely can, and some people do great with that. But if you've tried and struggled with consistency, a gym gives you accountability, variety, expert guidance, and a community. Most members say that's what made the difference." },
      { objection: "Memberships are too expensive", response: "We get it. That's why we offer plans starting at $X/month — less than $1/day. Plus, it's cheaper than dealing with health problems down the road. We also have a no-contract option so there's zero risk." },
    ],
    coldOutreachAngles: [
      "I run free 30-day fitness challenges for local businesses — it's great for team building and I handle everything. Interested in running one for your company?",
      "Your gym's Instagram has great content but low engagement — here are 3 quick fixes that doubled engagement for a gym like yours",
      "I noticed your Google listing doesn't show class times — that's the #1 thing people search for. Quick fix that drives walk-ins",
    ],
    seasonalEvents: [
      { month: "January", event: "New Year resolutions", postIdea: "New Year, new you? Join our January kickstart program — 30 days, zero judgment, real results." },
      { month: "February", event: "Valentine's", postIdea: "Love your body this Valentine's Day. Couples workout challenge starts this week!" },
      { month: "March", event: "Spring prep", postIdea: "Spring is coming — start your transformation now and feel amazing by summer." },
      { month: "May", event: "Summer body", postIdea: "6 weeks to summer. Our 6-Week Shred Challenge starts Monday. Limited spots." },
      { month: "June", event: "Summer", postIdea: "Summer classes are here: outdoor bootcamp, sunrise yoga, and more!" },
      { month: "August", event: "Back to routine", postIdea: "Kids back in school = your time. Get back to your fitness routine with our fall kickoff." },
      { month: "September", event: "Fall challenge", postIdea: "Fall fitness challenge: 30 days, new habits, serious results. Sign up free." },
      { month: "October", event: "Halloween", postIdea: "Spooky season workout: our Halloween themed HIIT class this Saturday. Costumes encouraged!" },
      { month: "November", event: "Holiday prep", postIdea: "Stay strong through the holidays. Our holiday survival workout plan keeps you on track." },
      { month: "December", event: "New Year prep", postIdea: "Don't wait for January 1. Start now and be ahead of everyone in the new year." },
    ],
  },
  {
    key: "salons",
    label: "Salons & Spas",
    singular: "salon",
    audience: "clients seeking hair, beauty, and wellness services",
    painPoints: [
      "No-shows and last-minute cancellations",
      "Difficulty rebooking clients consistently",
      "Building a social media presence that attracts clients",
      "Competing with budget chains",
      "Retail product sales are low",
    ],
    services: ["Haircuts & styling", "Color & highlights", "Blowouts", "Facials", "Manicures & pedicures", "Waxing", "Massage therapy", "Bridal services"],
    socialPlatforms: ["Instagram", "TikTok", "Facebook", "Pinterest"],
    hashtagSets: [
      ["#HairSalon", "#HairTransformation", "#SalonLife", "#BeautyPro", "#HairGoals"],
      ["#Balayage", "#HairColor", "#BlondeHair", "#HairCut", "#SalonStyle"],
      ["#NailArt", "#Facial", "#SpaDay", "#SelfCare", "#BeautyTips"],
    ],
    contentPillars: ["Before/after reveals", "Styling tutorials", "Product recommendations", "Team culture", "Client testimonials", "Seasonal trends"],
    seoKeywords: [
      { keyword: "hair salon near me", intent: "local", difficulty: "high", contentIdea: "Google Business optimization with portfolio photos and reviews" },
      { keyword: "balayage [city]", intent: "local-commercial", difficulty: "medium", contentIdea: "Portfolio page: Our best balayage transformations" },
      { keyword: "best hair color for my skin tone", intent: "informational", difficulty: "low", contentIdea: "Blog: How to choose the perfect hair color for your skin tone" },
      { keyword: "how to maintain colored hair", intent: "informational", difficulty: "low", contentIdea: "Blog: Stylist secrets to making your color last longer" },
      { keyword: "bridal hair [city]", intent: "local-commercial", difficulty: "medium", contentIdea: "Landing page: Bridal hair & makeup packages" },
      { keyword: "spa near me", intent: "local", difficulty: "high", contentIdea: "Google Business optimization + spa services landing page" },
      { keyword: "keratin treatment near me", intent: "local-commercial", difficulty: "low", contentIdea: "Blog: Everything you need to know about keratin treatments" },
      { keyword: "men's haircut [city]", intent: "local", difficulty: "medium", contentIdea: "Landing page: Men's grooming — cuts, beard trims, and more" },
      { keyword: "nail salon [city]", intent: "local", difficulty: "high", contentIdea: "Landing page: Manicure and pedicure services + nail art gallery" },
      { keyword: "hair salon gift cards", intent: "commercial", difficulty: "low", contentIdea: "Landing page: Gift the gift of self-care — digital gift cards" },
    ],
    emailSubjectLines: [
      "You're overdue for some self-care",
      "New look alert: Fall color trends are here",
      "Your stylist saved a spot for you",
      "Bring a friend, both get 20% off",
      "This is your sign to book that appointment",
    ],
    objections: [
      { objection: "It's cheaper to go to a chain salon", response: "You might save $10-20, but at a chain you get a different stylist each time, rushed service, and generic products. Here you get a stylist who knows your hair, uses premium products, and takes the time to get it right. Our clients stay because the results speak for themselves." },
      { objection: "I can do my own hair/nails", response: "Some things are great to DIY! But for color, cuts, and complex treatments, professional results are just different. Plus, it's your time to relax — you deserve to be taken care of." },
      { objection: "I don't know what I want", response: "That's totally fine! Our stylists love consultations. Show us what you like, what you don't, and we'll recommend options. The consultation is free and no-pressure." },
    ],
    coldOutreachAngles: [
      "Your Instagram content is beautiful but your bio is missing a booking link — that's the #1 way clients find you. Quick fix",
      "I noticed your salon doesn't show up on Google Maps for 'hair salon near me' — I put together a free audit showing why and how to fix it",
      "I help salons reduce no-shows by 50% using automated text reminders. Free 30-day trial, no commitment",
    ],
    seasonalEvents: [
      { month: "January", event: "New Year", postIdea: "New year, new look? Start fresh with a transformation. Book your January appointment!" },
      { month: "February", event: "Valentine's Day", postIdea: "Date night ready? Valentine's special: blowout + makeup for $X. Treat yourself." },
      { month: "March", event: "Spring refresh", postIdea: "Spring refresh: lighter color, fresh cut, new you. Our spring specials are live!" },
      { month: "April", event: "Prom season", postIdea: "Prom season is coming! Book your updo, makeup, and nails early — spots fill fast." },
      { month: "May", event: "Mother's Day", postIdea: "Mom deserves a spa day. Mother's Day gift packages available — treat the best woman you know." },
      { month: "June", event: "Wedding season", postIdea: "Bridal season is here! Book your bridal trial now for your summer wedding." },
      { month: "August", event: "Back to school", postIdea: "Back-to-school glow up! Fresh cuts and styles for students — special pricing this month." },
      { month: "September", event: "Fall trends", postIdea: "Fall hair color trend alert: warm coppers, rich brunettes, and buttery blondes. Which is you?" },
      { month: "October", event: "Halloween", postIdea: "Need a look for Halloween? Our team can create everything from glam to spooky." },
      { month: "December", event: "Holiday", postIdea: "Holiday party season! Book your glam appointment now — December fills up fast." },
    ],
  },
  {
    key: "ecommerce",
    label: "E-Commerce Stores",
    singular: "online store",
    audience: "online shoppers and retail customers",
    painPoints: [
      "High cart abandonment rates",
      "Rising ad costs with lower ROAS",
      "Building email list and repeat buyers",
      "Competing with Amazon and big retailers",
      "Inventory management and shipping logistics",
    ],
    services: ["Product sales", "Subscription boxes", "Wholesale", "Dropshipping", "Custom orders", "Gift sets"],
    socialPlatforms: ["Instagram", "TikTok", "Pinterest", "Facebook", "YouTube"],
    hashtagSets: [
      ["#ShopSmall", "#OnlineShopping", "#SmallBusiness", "#Ecommerce", "#ShopNow"],
      ["#NewArrivals", "#SaleAlert", "#GiftIdeas", "#TrendingNow", "#MustHave"],
      ["#ShopLocal", "#SmallBusinessOwner", "#HandmadeWithLove", "#BuySmall", "#ShopIndependent"],
    ],
    contentPillars: ["Product showcases", "Behind the scenes", "Customer reviews/UGC", "How-to/styling guides", "Flash sales", "Brand story"],
    seoKeywords: [
      { keyword: "[product type] online", intent: "commercial", difficulty: "varies", contentIdea: "Optimize product pages with rich descriptions and schema markup" },
      { keyword: "best [product] for [use case]", intent: "informational-commercial", difficulty: "medium", contentIdea: "Blog: Buyer's guide comparing your products for specific needs" },
      { keyword: "[product type] reviews", intent: "commercial", difficulty: "medium", contentIdea: "Blog: Honest review of our best-selling [product] (with customer photos)" },
      { keyword: "gifts for [person type]", intent: "commercial", difficulty: "medium", contentIdea: "Blog: Gift guide for [moms/dads/graduates/etc.] featuring your products" },
      { keyword: "[product] vs [competitor product]", intent: "commercial", difficulty: "low", contentIdea: "Blog: Honest comparison — why customers choose us" },
      { keyword: "free shipping [product type]", intent: "commercial", difficulty: "low", contentIdea: "Landing page: Free shipping on orders over $X" },
      { keyword: "sustainable [product type]", intent: "informational-commercial", difficulty: "low", contentIdea: "Blog: Our commitment to sustainability — materials, packaging, practices" },
      { keyword: "how to use [product]", intent: "informational", difficulty: "low", contentIdea: "Blog/video: Complete guide to getting the most from your [product]" },
      { keyword: "discount code [brand]", intent: "commercial", difficulty: "low", contentIdea: "Landing page: Current deals and discount codes" },
      { keyword: "[product type] subscription", intent: "commercial", difficulty: "low", contentIdea: "Landing page: Subscribe and save — monthly delivery at 20% off" },
    ],
    emailSubjectLines: [
      "This is selling fast (not a gimmick)",
      "Your cart is feeling lonely",
      "We made something new — you'll love it",
      "24 hours only: Free shipping on everything",
      "A little thank you for being a customer (discount inside)",
    ],
    objections: [
      { objection: "I can find this cheaper on Amazon", response: "You might find something similar, but not identical. Our products are [handmade/small-batch/ethically sourced/etc.], and when you buy from us, you're supporting a small business that puts quality over volume." },
      { objection: "What if it doesn't fit/work/look right?", response: "We offer hassle-free returns within 30 days. No restocking fees, no hoops to jump through. We want you to be 100% happy." },
      { objection: "Shipping takes too long", response: "We ship within 1-2 business days and most orders arrive in 3-5 days. We'll send you tracking the moment your order ships." },
    ],
    coldOutreachAngles: [
      "Your product photos are great but your site doesn't have customer reviews visible — adding them above the fold typically increases conversion by 15-25%",
      "I noticed your cart abandonment email sequence only has 1 email. A 3-email sequence recovers 2-3x more sales. Here's the framework",
      "Your site loads in 5+ seconds on mobile — that's costing you 30% of mobile shoppers. Quick fixes that make a big difference",
    ],
    seasonalEvents: [
      { month: "January", event: "New Year", postIdea: "New year sale! Start fresh with 20% off everything. Code: NEWYEAR. This week only." },
      { month: "February", event: "Valentine's Day", postIdea: "Valentine's gift guide: Perfect presents for your person. Order by Feb 10 for guaranteed delivery!" },
      { month: "March", event: "Spring launch", postIdea: "Spring collection just dropped. Fresh colors, new styles — shop the new arrivals." },
      { month: "May", event: "Mother's Day", postIdea: "Mother's Day is around the corner. Shop our curated gift sets — free gift wrapping included." },
      { month: "June", event: "Summer sale", postIdea: "Summer sale is ON. Up to 40% off selected items. Stock up for the sunny days ahead." },
      { month: "July", event: "Mid-year", postIdea: "Mid-year clearance: Last chance on these best-sellers before they're gone for good." },
      { month: "September", event: "Fall launch", postIdea: "Fall collection is here. Rich colors, cozy vibes, premium quality. Shop now." },
      { month: "October", event: "Pre-holiday", postIdea: "Early bird holiday shopping: Beat the rush and get 15% off with code EARLYBIRD." },
      { month: "November", event: "Black Friday", postIdea: "BLACK FRIDAY: Our biggest sale of the year. Up to 50% off everything. 48 hours only." },
      { month: "December", event: "Holiday/gift guide", postIdea: "Last-minute gift ideas with guaranteed delivery before Christmas. Free express shipping today!" },
    ],
  },
];

export function getNicheByKey(key: string): NicheData | undefined {
  return NICHES.find((n) => n.key === key);
}
